#!/usr/bin/env python3
import argparse
import math
from pathlib import Path

from typing import Any
from multiprocessing import Queue

from openpilot.tools.sim.bridge.metadrive.metadrive_bridge import MetaDriveBridge

def create_bridge(dual_camera, high_quality, test_duration=math.inf, test_run=False, simlab_config=None,
                  simulator="metadrive", carla_host="127.0.0.1", carla_port=2000, carla_town="Town04",
                  carla_route_asset=None):
  queue: Any = Queue()
  if simulator == "metadrive":
    simulator_bridge = MetaDriveBridge(dual_camera, high_quality, test_duration, test_run, simlab_config)
  elif simulator == "carla":
    if carla_route_asset is None:
      raise ValueError("--carla-route-asset is required for --simulator carla")
    from openpilot.tools.sim.bridge.carla.carla_bridge import CarlaBridge
    simulator_bridge = CarlaBridge(dual_camera, high_quality, host=carla_host, port=carla_port, town=carla_town,
                                   route_asset=str(carla_route_asset), test_duration=test_duration,
                                   test_run=test_run, simlab_config=simlab_config)
  else:
    raise ValueError(f"unsupported simulator: {simulator}")
  simulator_process = simulator_bridge.run(queue)

  return queue, simulator_process, simulator_bridge

def main():
  _, simulator_process, _ = create_bridge(True, False)
  simulator_process.join()

def parse_args(add_args=None):
  parser = argparse.ArgumentParser(description='Bridge between the simulator and openpilot.')
  parser.add_argument('--joystick', action='store_true')
  parser.add_argument('--high_quality', action='store_true')
  parser.add_argument('--dual_camera', action='store_true')
  parser.add_argument('--test-run', action='store_true')
  parser.add_argument('--test-duration', type=float, default=math.inf)
  parser.add_argument('--simlab-config', type=Path, help='YAML scenario generated by openpilot-sim-lab')
  parser.add_argument('--simulator', choices=('metadrive', 'carla'), default='metadrive')
  parser.add_argument('--carla-host', default='127.0.0.1')
  parser.add_argument('--carla-port', type=int, default=2000)
  parser.add_argument('--carla-town', default='Town04')
  parser.add_argument('--carla-route-asset', type=Path)

  return parser.parse_args(add_args)

if __name__ == "__main__":
  args = parse_args()

  simlab_config = None
  if args.simlab_config:
    import yaml
    with args.simlab_config.open() as f:
      simlab_config = yaml.safe_load(f) or {}
  queue, simulator_process, simulator_bridge = create_bridge(args.dual_camera, args.high_quality,
                                                              args.test_duration, args.test_run, simlab_config,
                                                              args.simulator, args.carla_host, args.carla_port,
                                                              args.carla_town, args.carla_route_asset)

  if args.joystick:
    # start input poll for joystick
    from openpilot.tools.sim.lib.manual_ctrl import wheel_poll_thread

    wheel_poll_thread(queue)
  else:
    # start input poll for keyboard
    from openpilot.tools.sim.lib.keyboard_ctrl import keyboard_poll_thread

    keyboard_poll_thread(queue)

  simulator_bridge.shutdown()

  simulator_process.join()
